[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt"
  publish = "public"  # Remplacez "public" par le dossier de publication de votre application (souvent "build" ou "dist" pour certains projets)

